// Generated by CoffeeScript 1.7.1
(function() {
  var Identifier, Node, PROBLEMATIC_NAMES, RESERVED, UNRESERVED, construct, identifierPart, identifierStart, randomElement, randomInt, scribbler, _ref,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = require('../node');

  RESERVED = require('../reserved');

  UNRESERVED = require('../unreserved');

  _ref = require('../random'), randomInt = _ref.randomInt, randomElement = _ref.randomElement;

  construct = require('../combinators').construct;

  scribbler = require('../scribbler');

  PROBLEMATIC_NAMES = __slice.call(RESERVED).concat(__slice.call(UNRESERVED));

  identifierStart = identifierPart = function() {
    return String.fromCharCode(97 + randomInt(25));
  };

  Identifier = (function(_super) {
    __extends(Identifier, _super);

    Identifier.prototype.type = Identifier.name;

    function Identifier() {
      if (Math.random() < 1 / 10) {
        this.name = randomElement(PROBLEMATIC_NAMES);
      } else {
        this.name = scribbler.id();
      }
    }

    return Identifier;

  })(Node);

  module.exports = construct(Identifier);

}).call(this);
