// Generated by CoffeeScript 1.7.1
(function() {
  var Node, String_, randomInt, scribbler,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = require('../node');

  randomInt = require('../random').randomInt;

  scribbler = require('../scribbler');

  String_ = (function(_super) {
    __extends(String_, _super);

    String_.prototype.type = 'Literal';

    function String_() {
      this.value = scribbler.string();
    }

    return String_;

  })(Node);

  module.exports = function() {
    return new String_;
  };

}).call(this);
